DEFINE TABLE CICD_DEMO{{env_suffix}}.PROJECTS1.CUSTOMER (
    CUSTOMER_ID VARCHAR NOT NULL,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE CICD_DEMO{{env_suffix}}.PROJECTS1.EMPLOYEE (
    EMPLOYEE_ID VARCHAR NOT NULL,
    EMPLOYEE_NAME VARCHAR NOT NULL,
    DEPARTMENT VARCHAR,
    DESIGNATION VARCHAR,
    SALARY NUMBER(10,2),
    JOIN_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


DEFINE TABLE CICD_DEMO{{env_suffix}}.PROJECTS1.CUSTOMER_test (
    CUSTOMER_ID VARCHAR NOT NULL,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


